name: ${project.artifactId}
author: WizardlyBump17
main: com.wizardlybump17.nosee.${project.artifactId}
version: ${project.version}
softdepend: [WLib]
commands:
  vanish:
    permission: nosee.vanish
    aliases: [v]